import fs from 'node:fs';
import crypto from 'node:crypto';
import {releaseProvenance} from './release-provenance.mjs';
const source=fs.readFileSync('runtime/nexus-runtime.js');
const manifest=JSON.parse(fs.readFileSync('extension/manifest.json'));
const expected=releaseProvenance();
if(crypto.createHash('sha256').update(source).digest('hex')!==expected.sourceRuntimeSha256)throw Error('Runtime differs from reviewed release source');
const text=source.toString(),a=text.indexOf("const RULES_KEY = 'nexusRequirementRulesV1';"),b=text.indexOf('\n(() => {\n  // Each mission document keeps a fixed rule set',a);
if(a<0||b<0||text.slice(a,b).trim()!==fs.readFileSync('extension/rules-core.mjs','utf8').replace(/^export /gm,'').trim())throw Error('Embedded rules module drifted from rules-core.mjs');
if(!source.toString().includes("build: '"+manifest.version+"'"))throw Error('Runtime and manifest version differ');
fs.writeFileSync('extension/nexus-runtime.js',source);
console.log('Prepared reviewed runtime '+manifest.version+' without regenerating an older build.');
