import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const code=fs.readFileSync('extension/google-backend/Code.gs','utf8')+'\n'+fs.readFileSync('extension/google-backend/Rolling.gs','utf8');
function setup(){const c=vm.createContext({Date,console,Utilities:{formatDate:d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}});vm.runInContext(code,c);return c;}
const state=()=>({missions:{},credits:{}});
const event=(id,type,at='2026-09-08T06:00:00Z',extra={})=>({id,player:'419938',at:Date.parse(at),kind:'mission',record:{missionId:'260428689',eventType:type,...extra}});
test('replay preserves earliest capture day and never doubles dispatch or unit totals',()=>{const c=setup(),s=state(),e=event('a','dispatch',undefined,{firstObservedAt:'2026-09-08T05:00:00Z',units:[{vehicleId:'1'},{vehicleId:'2'}]});c.nx2ReduceMission(s,e);c.nx2ReduceMission(s,JSON.parse(JSON.stringify(e)));const d=c.nx2Totals(s,new Date())[0];assert.equal(d[3],1);assert.equal(d[8],1);assert.equal(d[9],2);assert.equal(d[0],'2026-09-08');});
test('late backlog corrects first-observed date without replacing newer metadata',()=>{const c=setup(),s=state();c.nx2ReduceMission(s,event('a','mission-observed',undefined,{missionName:'New'}));c.nx2ReduceMission(s,event('b','mission-observed','2026-09-06T23:30:00Z',{missionName:'Old'}));const d=c.nx2Totals(s,new Date())[0];assert.equal(d[0],'2026-09-07');assert.equal(s.missions['260428689'].row[4],'New');});
test('transaction retries count once and conflicting amounts fail',()=>{const c=setup(),s=state(),e=event('a','mission-credit',undefined,{transactionId:'tx',transactionAt:'2026-09-07T23:30:00Z',actualCredits:7300000});c.nx2ReduceCredit(s,e);c.nx2ReduceCredit(s,e);const d=c.nx2Totals(s,new Date())[0];assert.equal(d[0],'2026-09-08');assert.equal(d[7],7300000);assert.throws(()=>c.nx2ReduceCredit(s,{...e,record:{...e.record,actualCredits:1}}),/Conflicting/);});
test('missing advertised value never becomes actual income and completion requires evidence',()=>{const c=setup(),s=state();c.nx2ReduceMission(s,event('a','mission-completed',undefined,{advertisedCredits:9000}));assert.equal(s.missions['260428689'].row[9],'');c.nx2ReduceMission(s,event('b','mission-completed',undefined,{completionVerified:true}));const d=c.nx2Totals(s,new Date())[0];assert.equal(d[5],1);assert.equal(d[7],0);assert.equal(d[16],1);});
test('combines compact shard totals using weighted means',()=>{const c=setup(),a=state(),b=state();c.nx2ReduceMission(a,event('a','dispatch',undefined,{firstObservedAt:'2026-09-08T05:59:00Z'}));c.nx2ReduceMission(b,event('b','dispatch',undefined,{firstObservedAt:'2026-09-08T05:57:00Z'}));const d=c.nx2Combine([...c.nx2Totals(a,new Date()),...c.nx2Totals(b,new Date())],new Date())[0];assert.equal(d[3],2);assert.equal(d[14],120);});
test('mission shard identity is stable across restarts and days',()=>{const c=setup();assert.equal(c.nx2MissionBucket('1','12345'),'m-1-12');assert.notEqual(c.nx2MissionBucket('2','12345'),c.nx2MissionBucket('1','12345'));});
test('large batches resume at an event offset with at most four mission buckets per chunk',()=>{const c=setup(),events=Array.from({length:30},(_,i)=>event(String(i),'mission-observed',undefined,{missionId:String(1000*i)})),body={events};let offset=0;const ids=[];while(offset<events.length){const chunk=c.nx2Chunk(body,offset);assert.ok(chunk.events.length<=4);ids.push(...chunk.events.map(e=>e.id));offset+=chunk.events.length;}assert.deepEqual(ids,events.map(e=>e.id));});
test('archive rolls before the cell limit and an interrupted receipt keeps its assigned part',()=>{
 const c=setup(),props=new Map([['NX2_ACTIVE_PART','old']]),books=new Map(),indexed=[];
 function book(id,cells){const sheet={getMaxRows:()=>cells/10,getMaxColumns:()=>10,setName(){},getRange:()=>({setValues(){}})};return {getId:()=>id,getSheets:()=>[sheet],setSpreadsheetTimeZone(){}};}
 books.set('old',book('old',1999990));let creates=0;
 c.PropertiesService={getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v)})};
 c.SpreadsheetApp={openById:id=>books.get(id),create:()=>{const b=book('new',10000);books.set('new',b);creates++;return b;}};
 c.DriveApp={getFileById:()=>({moveTo(){}})};c.nx2IndexPart=(_,b,status)=>indexed.push([b.getId(),status]);c.nx2Save=()=>{};
 const ctx={raw:new Map()},receipt={value:{}};
 assert.equal(c.nx2Part(ctx,receipt,50).getId(),'new');assert.equal(receipt.value.partId,'new');assert.equal(creates,1);
 assert.equal(c.nx2Part(ctx,{value:{partId:'old'}},50).getId(),'old');assert.equal(creates,1);assert.deepEqual(indexed,[['old','SEALED']]);
});
test('failed archive verification cannot mark a receipt complete',()=>{const c=setup();c.nxStore=()=>{throw Error('write failed');};const receipt={value:{status:'PENDING'}};const ctx={pending:[{receipt,body:{}}],raw:new Map([['p',{part:{},sheet:{},rows:[[1]]}]]),docs:new Map()};assert.throws(()=>c.nx2Flush(ctx),/write failed/);assert.equal(receipt.value.status,'PENDING');assert.equal(ctx.pending.length,1);});
test('pipeline reserves processing for fresh files before backlog and backfill',()=>{const c=setup(),calls=[],p=new Map();c.PropertiesService={getScriptProperties:()=>({getProperty:k=>p.get(k),setProperty:(k,v)=>p.set(k,v),deleteProperty:k=>p.delete(k)})};c.LockService={getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})};c.nx2Context=()=>({});c.nx2Queue=(_,name)=>calls.push(name);c.nx2Publish=()=>calls.push('publish');c.nx2Backfill=()=>calls.push('backfill');c.nexusRollingTick();assert.deepEqual(calls,['Extension Pending Live Imports','publish','Extension Pending Imports','publish','backfill','publish']);});
