import {meaningful} from './collector-core.mjs';
export class CollectorStore{
 constructor(idb=globalThis.indexedDB,name='nexusPrivateCollectorV1'){this.idb=idb;this.name=name;}
 async db(){if(!this.opening)this.opening=new Promise((resolve,reject)=>{const r=this.idb.open(this.name,2);r.onupgradeneeded=()=>{const d=r.result;const q=d.objectStoreNames.contains('events')?r.transaction.objectStore('events'):d.createObjectStore('events',{keyPath:'event_id'});if(!q.indexNames.contains('queuedAt'))q.createIndex('queuedAt','queuedAt');if(!q.indexNames.contains('playerQueuedAt'))q.createIndex('playerQueuedAt',['player','queuedAt']);if(!d.objectStoreNames.contains('seen'))d.createObjectStore('seen',{keyPath:'key'});if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta');};r.onsuccess=()=>{r.result.onversionchange=()=>{r.result.close();this.opening=null;};resolve(r.result);};r.onerror=()=>reject(r.error);}).catch(e=>{this.opening=null;throw e;});return this.opening;}
 async transact(stores,mode,work){const d=await this.db();return new Promise((resolve,reject)=>{const t=d.transaction(stores,mode);let result;try{result=work(t);}catch(e){t.abort();reject(e);return;}t.oncomplete=()=>resolve(typeof result==='function'?result():result);t.onabort=t.onerror=()=>reject(t.error||Error('Collector storage unavailable'));});}
 async meta(){let v;await this.transact(['meta'],'readonly',t=>{const r=t.objectStore('meta').get('state');r.onsuccess=()=>v=r.result;});return v||{enabled:true,deviceLabel:'Nexus private browser',attempts:0,nextAttempt:0,lastError:'',lastSuccess:0};}
 async update(patch){let v;await this.transact(['meta'],'readwrite',t=>{const s=t.objectStore('meta'),r=s.get('state');r.onsuccess=()=>{v={enabled:true,deviceLabel:'Nexus private browser',...(r.result||{}),...patch};s.put(v,'state');};});return v;}
 async capture(inputs){const events=inputs.map(meaningful).filter(Boolean);for(const n of events)if(n.idKey){const bytes=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(n.idKey)));n.stableId=Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("");}let added=0;await this.transact(['events','seen','meta'],'readwrite',t=>{
  const queue=t.objectStore('events'),seen=t.objectStore('seen');
  // Sequence requests inside the transaction so duplicate entries in one batch
  // observe the previous write, not the same old fingerprint.
  const next=i=>{if(i===events.length)return;const n=events[i],r=seen.get(n.seenKey);r.onsuccess=()=>{if(r.result?.fingerprint!==n.fingerprint){queue.add({...n.event,event_id:n.stableId||crypto.randomUUID(),player:n.who.player,username:n.who.username,queuedAt:Date.now()});seen.put({key:n.seenKey,fingerprint:n.fingerprint,at:Date.now()});added++;}next(i+1);};};next(0);
 });return added;}
 async batch(player,limit=50){const rows=[];await this.transact(['events'],'readonly',t=>{const r=t.objectStore('events').index('playerQueuedAt').openCursor(IDBKeyRange.bound([player,0],[player,Number.MAX_SAFE_INTEGER]));r.onsuccess=()=>{const c=r.result;if(!c||rows.length>=limit)return;rows.push(c.value);c.continue();};});return rows;}
 async ack(ids){await this.transact(['events','meta'],'readwrite',t=>{const s=t.objectStore('events');for(const id of ids)s.delete(id);const m=t.objectStore('meta'),r=m.get('state');r.onsuccess=()=>m.put({...r.result,lastSuccess:Date.now(),lastError:'',attempts:0,nextAttempt:0},'state');});}
 async stats(){let count=0,oldest=0;await this.transact(['events'],'readonly',t=>{const s=t.objectStore('events'),c=s.count();c.onsuccess=()=>count=c.result;const r=s.index('queuedAt').openCursor();r.onsuccess=()=>oldest=r.result?.value.queuedAt||0;});return {pending:count,oldest};}
 async export(){let events=[];await this.transact(['events'],'readonly',t=>{const r=t.objectStore('events').getAll();r.onsuccess=()=>events=r.result;});return events;}
}
