import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {devLibrary} from '../../scripts/dev-library.mjs';
const {chromium}=devLibrary('playwright');
const report={version:'3.0.43.53',realGame:false,source:'Card selectors and action structure from jxn-30/LSS-Scripts cleanerVehicleMarket and vehicleMarketShowAmount; fixtures reconstructed, no live account writes.',checks:[],errors:[],writes:[]};
const pass=s=>{report.checks.push(s);console.log('PASS '+s);};
const scripts=['nexus-settings-main.js','nexus-home-market.js'].map(f=>fs.readFileSync('extension/'+f,'utf8'));
const old=execFileSync('git',['show','d4f6f256:browser-extension/extension/nexus-home-market.js'],{encoding:'utf8'});
const html=body=>`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="fixture-only"><style>body{margin:12px;background:#505050;color:white;font:14px Arial}.tab-pane{display:none}.nx-building-right{max-width:800px}h3{font-size:15px}</style></head><body>${body}</body></html>`;
let full=false,mode='ok';
const building=()=>html(`<h1>Home Response location</h1><dl class="dl-horizontal"><dt>Vehicles:</dt><dd>${full?'1':'0'} of 1 <a href="/buildings/23/vehicles/new">Vehicle Market</a></dd></dl><div class="nx-building-right"><section id="nx-expansions">Nexus · Building extensions</section></div>`);
const card=(type,name,price,{disabled=false,post=false,note='',coin=25}={})=>`<div class="col-sm-3"><div class="well vehicle_type"><h3>${name}</h3>${note?`<div class="alert alert-info">${note}</div>`:''}<p><a class="btn buy-vehicle-btn ${disabled?'disabled':''}" ${post?'data-method="post" data-confirm="Buy this unit?"':''} href="/buildings/23/vehicle/23/${type}/credits?building=23"><span class="glyphicon glyphicon-piggy-bank"></span> ${price}</a><a class="btn buy-vehicle-btn" href="/buildings/23/vehicle/23/${type}/coins?building=23">${coin}</a></p></div></div>`;
const market=()=>html(`<ul id="tabs"><li><a href="#fire">Fire</a></li><li><a href="#ambulance">Ambulance</a></li><li><a href="#police">Police</a></li></ul><div class="tab-content"><div id="fire" class="tab-pane"><div class="vehicle-market-subcategory"><h2>Fire command</h2>${card(3,'Fire Officer','5,000',{note:'Required once you have built 6 Fire Station'})}</div></div><div id="ambulance" class="tab-pane">${card(21,'Rapid Response Vehicle','4,000',{note:'Required once you have built 6 Rescue stations'})}${card(73,'Ambulance Officer','15,000',{disabled:true,note:'Requires special education (Ambulance Officer)'})}${card(80,'Operational Team Leader','25,000',{post:true,note:'Required once you have built 15 Rescue stations'})}</div><div id="police" class="tab-pane">${card(8,'IRV','5,000')}${mode==='unsafe'?card(9,'Unsafe','100').replaceAll('/buildings/23/vehicle/23/9/','/buildings/24/vehicle/24/9/'):''}</div></div>`);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
async function context(content){const c=await browser.newContext({viewport:{width:1000,height:800}});await c.addInitScript(texts=>document.addEventListener('DOMContentLoaded',()=>texts.forEach(t=>{const s=document.createElement('script');s.textContent=t;document.head.append(s);})),content);await c.route('https://**/*',async route=>{
 const r=route.request(),u=new URL(r.url());if(u.origin!=='https://www.missionchief.co.uk')return route.abort();
 if(u.pathname==='/api/buildings/23')return route.fulfill({json:{id:23,building_type:22}});
 if(u.pathname==='/buildings/23/vehicles/new'){let body=market();if(mode==='no-csrf')body=body.replace(/<meta name="csrf-token"[^>]*>/,'');if(mode==='unsafe')body=body.replace('/vehicle/23/21/credits','/vehicle/24/21/credits').replace('/3/credits?building=23','/3/credits?building=24');return route.fulfill({contentType:'text/html',body});}
 if(u.pathname.includes('/vehicle/')){report.writes.push({path:u.pathname,query:u.search,method:r.method(),body:[...new URLSearchParams(r.postData()||'')]});if(mode==='reject')return route.fulfill({contentType:'text/html',body:html('<div class="alert alert-danger">Purchase rejected.</div>')});full=true;return route.fulfill({contentType:'text/html',body:html('<div class="alert alert-success">Vehicle purchased.</div>')});}
 return route.fulfill({contentType:'text/html',body:mode==='no-csrf'?building().replace(/<meta name="csrf-token"[^>]*>/,''):building()});
 });return c;}
let ctx;
try{
 ctx=await context([scripts[0],old]);let p=await ctx.newPage();await p.goto('https://www.missionchief.co.uk/buildings/23');await p.getByText(/No inline purchase options/).waitFor();assert.equal(await p.locator('#nx-home-market tbody tr').count(),0);assert.match(await p.locator('#nx-home-market').innerText(),/Required once you have built 6 Fire Station/);await ctx.close();pass('Reproduces .52: documented native vehicle cards produce zero offers and an unrelated requirement-message block');
 ctx=await context(scripts);p=await ctx.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>report.errors.push(e.message));const open=async()=>{await p.goto('https://www.missionchief.co.uk/buildings/23');await p.locator('#nx-home-market tbody tr').first().waitFor();};await open();const root=p.locator('#nx-home-market');
 assert.equal(await root.locator('tbody tr').count(),5);assert.equal(await root.locator('select,input[type=search]').count(),0);assert.ok(!(await root.innerText()).includes('Required once'));assert.equal(await root.evaluate(n=>n.previousElementSibling.id),'nx-expansions');
 const row=name=>root.locator('tbody tr').filter({hasText:name});assert.equal(await row('Fire Officer').locator('td').first().innerText(),'Fire command');assert.equal(await row('Rapid Response Vehicle').locator('td').first().innerText(),'Ambulance');
 assert.equal(await row('Fire Officer').getByRole('link',{name:'Buy · 5,000 credits',exact:true}).count(),1);assert.equal(await root.locator('[href*="/coins"]').count(),0);assert.equal(await row('Ambulance Officer').getByRole('button').isDisabled(),true);assert.equal(report.writes.length,0);await root.screenshot({path:'audit/quick-buy-53.png'});pass('Each native card becomes one compact category/name/Buy row; icon-only prices work, credits are preferred, unavailable credit purchases do not fall back to coins');
 await row('Fire Officer').getByRole('link').evaluate(a=>{a.click();a.click();});await p.waitForURL('**/buildings/23');await root.getByText('No free vehicle space at this location.').waitFor();assert.equal(report.writes.length,1);assert.deepEqual(report.writes[0],{path:'/buildings/23/vehicle/23/3/credits',query:'?building=23',method:'GET',body:[]});assert.equal(await root.locator('a.nx-buy,button.nx-buy:not(:disabled)').count(),0);pass('Quick buy uses the exact native credits action once and returns to the same building; full capacity blocks another purchase');
 full=false;await open();p.once('dialog',d=>d.accept());await row('Operational Team Leader').getByRole('button').click();await p.waitForURL('**/buildings/23');await root.getByText('No free vehicle space at this location.').waitFor();assert.equal(report.writes.length,2);assert.equal(report.writes[1].method,'POST');assert.deepEqual(report.writes[1].body,[['authenticity_token','fixture-only']]);pass('Native POST buy links preserve their method, confirmation and CSRF instead of guessing a GET');
 full=false;mode='reject';await open();await row('IRV').getByRole('link').click();await p.getByText('Purchase rejected.').waitFor();assert.match(p.url(),/\/vehicle\/23\/8\/credits/);assert.equal(report.writes.length,3);pass('A rejected purchase stays on the game response and is never retried');
 mode='unsafe';await open();assert.equal(await row('Unsafe').getByRole('button',{name:'Unavailable'}).isDisabled(),true);assert.equal(await row('Rapid Response Vehicle').getByRole('button',{name:'Unavailable'}).isDisabled(),true);assert.equal(await row('Fire Officer').getByRole('button',{name:'Unavailable'}).isDisabled(),true);assert.equal(await root.locator('[href*="buildings/24"],[href*="building=24"],[href*="vehicle/24"]').count(),0);
 mode='no-csrf';await open();assert.equal(await row('Operational Team Leader').getByRole('button',{name:'Unavailable'}).isDisabled(),true);assert.equal(await row('Operational Team Leader').locator('[href*="/coins"]').count(),0);pass('Missing POST tokens and mismatched building IDs cannot substitute a coin offer or target another building');mode='ok';await open();
 const cdp=await ctx.newCDPSession(p);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await p.setViewportSize({width:390,height:844});await p.evaluate(()=>document.documentElement.dataset.nexusTouch='true');const box=await root.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390);for(const b of await root.locator('a.nx-buy,button').all())assert.ok((await b.boundingBox()).height>=44);await root.screenshot({path:'audit/quick-buy-53-phone.png'});pass('Quick-buy rows fit phone widths with usable buttons; foreign-building offers cannot become active controls');
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.failure=String(e);throw e;}finally{await browser.close();fs.writeFileSync('audit/quick-buy-53.json',JSON.stringify(report,null,2)+'\n');}
