import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {devLibrary} from '../../scripts/dev-library.mjs';
import {releaseProvenance} from '../../scripts/release-provenance.mjs';
import {commandToolbarFixture} from './command-toolbar-fixture.mjs';import {vehicleRow} from './vehicle-tabs-fixture.mjs';
import {buildingFleet,buildingPersonnel,buildingOverviewFixture} from './building-overview-fixture.mjs';
const base='extension';
const report={version:JSON.parse(fs.readFileSync(base+'/manifest.json')).version,realGame:false,checks:[],errors:[],requests:[]},pass=name=>{report.checks.push(name);console.log('PASS '+name);};
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
for(const file of new Set(JSON.parse(fs.readFileSync(base+'/manifest.json')).content_scripts.flatMap(s=>s.js)))new vm.Script(fs.readFileSync(base+'/'+file,'utf8'),{filename:file});
assert.equal(hash(fs.readFileSync(base+'/nexus-runtime.js')),releaseProvenance().sourceRuntimeSha256);
pass('Packaged JavaScript parses and Auto runtime matches the reviewed release source');
const stored=new Map([['mf_event_scanner_enabled_v1','false'],['mf_mission_ready_delay_ms','1500'],['nexusManualTransportShortcutsV1','{"autoOpenTransportRequest":false,"autoClickSuccessBtns":true}'],['unrelated-queue','retain']]);let reads=0;
const sandbox={localStorage:{getItem:k=>{reads++;return stored.get(k)??null;},setItem:(k,v)=>stored.set(k,v)},window:{dispatchEvent(){}},Event:class{}};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync(`${base}/nexus-settings.js`,'utf8'),sandbox);vm.runInContext(fs.readFileSync(`${base}/nexus-settings-defaults.js`,'utf8'),sandbox);
const S=sandbox.NexusSettings,draft=S.snapshot(sandbox.NexusSettingsDefaults);
assert.equal(draft.runtime.eventScanner,false);assert.equal(draft.runtime.readyDelay,1500);assert.equal(draft.transport.autoOpenTransportRequest,false);
const before=new Map(stored);draft.runtime.readyDelay=12;assert.throws(()=>S.save(draft));assert.deepEqual(stored,before);draft.runtime.readyDelay=2000;draft.features.currency=false;S.save(draft);assert.equal(stored.get('unrelated-queue'),'retain');assert.equal(stored.get('mf_ready_delay_10_6_58_migrated'),'true');
const count=reads;for(let i=0;i<10000;i++)S.enabled('currency');assert.equal(reads,count);S.applyFlags(undefined);
pass('Existing settings migrate without resets; invalid delay is rejected before writes; feature checks do no storage reads in hot loops');
const {chromium}=devLibrary('playwright');const context=await chromium.launchPersistentContext(path.resolve(`audit/settings43-profile-${Date.now()}`),{executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,viewport:{width:1280,height:940},args:[`--disable-extensions-except=${path.resolve(base)}`,`--load-extension=${path.resolve(base)}`],ignoreDefaultArgs:['--disable-extensions']});
const home='<!doctype html><html><head><style>body{background:#505050;color:white;font:14px Arial}.navbar-header{height:50px;background:#c83225}.navbar-brand{float:left;padding:12px;color:white}.navbar-right{float:right}iframe{display:block;width:1150px;height:650px}</style></head><body><div class="navbar-header"><a class="navbar-brand" href="/">MissionChief</a><div class="navbar-right"><a id="navigation_top" href="/credits"><span class="credits-value">7,300,000</span></a><a id="coins_top" href="/coins"><span class="coins-value">200</span></a></div></div><div id="map"></div><a id="navbar_profile_link" href="/profile/123">Fixture</a><div id="missions-panel-body"><div class="missionSideBarEntry" id="mission_81" mission_id="81" mission_type_id="756" data-additive-overlays="a"><div><div id="mission_bar_outer_81"><div class="progress-bar"></div></div></div></div></div></body></html>';
const mission=commandToolbarFixture().replace('<form id="mission-form">','<div id="mission_general_info" data-generation-time="2026-09-12T12:00:00Z"><small>Fixture mission</small></div><div id="missing_text"><div data-requirement-type="other"><b>Other information:</b> 2 Cars to tow</div><div data-requirement-type="vehicles"><b>Missing Vehicles:</b> 1 Ambulance</div></div><form id="mission-form">').replace('</tbody></table>',vehicleRow(111,105,'Flatbed')+'</tbody></table>');
try{
 await context.addInitScript(()=>{window.fixtureIntervals=new Map();const set=window.setInterval,clear=window.clearInterval;window.setInterval=function(fn,ms,...args){const id=set(fn,ms,...args);window.fixtureIntervals.set(id,ms);return id;};window.clearInterval=function(id){window.fixtureIntervals.delete(id);return clear(id);};});
 await context.route('https://**/*',route=>{const u=new URL(route.request().url());if(u.origin!=='https://www.missionchief.co.uk'){report.requests.push('blocked external: '+u.hostname);return route.abort();}
 if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:home});
 if(u.pathname==='/leitstellenansicht')return route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><style>body{background:#505050;color:white;font:14px Arial}</style></head><body><a class="lightbox-open list-group-item active" href="/buildings/1">Fixture Fire Station</a></body></html>'});
 if(u.pathname==='/fixture-worker-host')return route.fulfill({contentType:'text/html',body:'<!doctype html><html><body><h1>Isolated worker host fixture</h1></body></html>'});
 if(u.pathname.startsWith('/missions/'))return route.fulfill({contentType:'text/html',body:mission});
 if(u.pathname==='/buildings/1')return route.fulfill({contentType:'text/html',body:buildingOverviewFixture()});
 if(u.pathname==='/buildings/1/personals')return route.fulfill({contentType:'text/html',body:buildingPersonnel()});
 if(u.pathname==='/api/buildings/1/vehicles')return route.fulfill({contentType:'application/json',body:JSON.stringify(buildingFleet.filter(v=>v.building_id===1))});
 if(u.pathname==='/api/userinfo')return route.fulfill({contentType:'application/json',body:'{"credits_user_total":655760580}'});
 if(u.pathname==='/api/buildings')return route.fulfill({contentType:'application/json',body:'[]'});
 report.requests.push(u.pathname);return route.fulfill({contentType:'application/json',body:'[]'});
 });
 const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.setDefaultTimeout(12000);
 await page.goto('https://www.missionchief.co.uk/');const tools=page.locator('#nexus-native-tools');await tools.locator('#toggle').waitFor();const rect=await tools.locator('#toggle').boundingBox();assert.ok(rect.x>1100&&rect.y<25);await tools.locator('#toggle').click();
 assert.equal(await page.evaluate(()=>window.__NEXUS_EXTENSION__.build),JSON.parse(fs.readFileSync(base+'/manifest.json')).version);
 assert.deepEqual(await tools.locator('#tabs button').allTextContents(),['Overview','Buildings','Vehicles','Schooling','Settings']);
 assert.equal(await tools.locator('#toggle').isVisible(),false,'Standalone launcher must not cover the dialog close button');
 await tools.locator('[data-view=settings]').click();assert.equal(await tools.locator('input[role=switch]').count(),40);
 pass('Packaged extension loads with five Tools tabs, top-right launcher and 40 on/off switches under actual extension CSP');
 await page.screenshot({path:'audit/settings-43-wide.png'});
 const setting=id=>tools.locator(`[data-setting-id="${id}"]`);
 const scannerPage=await context.newPage();scannerPage.on('pageerror',e=>report.errors.push(e.message));scannerPage.setDefaultTimeout(12000);await scannerPage.goto('https://www.missionchief.co.uk/missions/10');await scannerPage.locator('#mission-finder-wrapper').waitFor();
 const timers=()=>scannerPage.evaluate(()=>[...fixtureIntervals.values()].filter(ms=>ms===15000).length);
 const started=await timers();assert.ok(started>=1,'Event scanner timer should be running');
 await setting('eventScanner').uncheck();await setting('autoOpenTransportRequest').uncheck();await setting('missingAmbulance').check();await setting('readyDelay').fill('2500');await tools.locator('#saveSettings').click();await tools.locator('#settingsStatus').filter({hasText:'Saved.'}).waitFor();
 await scannerPage.waitForFunction(count=>[...fixtureIntervals.values()].filter(ms=>ms===15000).length===count,started-1);assert.equal(await page.evaluate(()=>localStorage.getItem('mf_high_risk_missing_person_ambulance_v1')),'true');
 await setting('eventScanner').check();await tools.locator('#saveSettings').click();await scannerPage.waitForFunction(count=>[...fixtureIntervals.values()].filter(ms=>ms===15000).length===count,started);
 await tools.locator('#saveSettings').click();assert.equal(await timers(),started);
 pass('Event Scanner stops and restarts its existing collector immediately, without duplicate timers; original dispatch keys receive saved values');
 await scannerPage.close();
 await page.reload();await tools.locator('#toggle').click();await tools.locator('[data-view=settings]').click();assert.equal(await setting('readyDelay').inputValue(),'2500');assert.equal(await setting('autoOpenTransportRequest').isChecked(),false);assert.equal(await setting('missingAmbulance').isChecked(),true);
 pass('Mission and transport choices survive page reload and read back correctly in Settings');
 await page.setViewportSize({width:390,height:820});await page.screenshot({path:'audit/settings-43-narrow.png'});const box=await tools.locator('#panel').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390);assert.equal(await tools.locator('#body').evaluate(n=>n.scrollWidth>n.clientWidth),false);await page.setViewportSize({width:1280,height:940});
 pass('Settings remains inside a 390px viewport without horizontal overflow');
 // Every display feature is disabled in one save; fresh documents must retain the game UI.
 await tools.locator('[data-setting-kind=features]').evaluateAll(inputs=>inputs.forEach(input=>{input.checked=false;input.dispatchEvent(new Event('change',{bubbles:true}));}));await tools.locator('#saveSettings').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('nexusConveniencesV1')).currency===false);await page.reload();
  assert.equal(await page.evaluate(()=>NexusSettings.enabled('currency')),false);
  assert.equal(await page.locator('#nx-currency-menu').count(),0);assert.equal(await page.locator('[data-nx-mission-reward]').count(),0);
 const manual=await context.newPage();manual.on('pageerror',e=>report.errors.push(e.message));manual.setDefaultTimeout(12000);await manual.goto('https://www.missionchief.co.uk/missions/10');
 await manual.locator('#mission-finder-wrapper').waitFor();assert.deepEqual(await manual.locator('[data-mf-dashboard-tab]').allTextContents(),['\n                01\n                Mission\n            ']);assert.equal(await manual.locator('#mf-dashboard-utility').count(),0);
 assert.equal(await manual.locator('#nx-missing').count(),0);assert.equal(await manual.locator('#nx-vehicle-tabs').count(),0);assert.equal(await manual.locator('#nx-command-tools').count(),0);assert.equal(await manual.locator('ul#tabs').isVisible(),true);assert.equal(await manual.locator('#nx-transport-shortcuts').count(),0);
 await manual.locator('#vehicle_2').check();await manual.locator('#dispatch').click();assert.deepEqual(await manual.evaluate(()=>dispatches),[['2']]);
 pass('Fresh mission has Mission only, no old settings/diagnostic panes; disabled enhancements restore native tabs and native dispatch works');
 // Naming panel uses the actual runtime CSS, with a small-screen maximum.
 const naming=await context.newPage();naming.on('pageerror',e=>report.errors.push(e.message));naming.setDefaultTimeout(12000);await naming.goto('https://www.missionchief.co.uk/leitstellenansicht');await naming.locator('#mc-namer-panel').waitFor({state:'visible'});const width=await naming.locator('#mc-namer-panel').evaluate(n=>parseFloat(getComputedStyle(n).width));assert.equal(width,440);await naming.screenshot({path:'audit/settings-43-naming.png'});await naming.setViewportSize({width:390,height:820});const narrowWidth=await naming.locator('#mc-namer-panel').evaluate(n=>parseFloat(getComputedStyle(n).width));assert.ok(narrowWidth<=374);await naming.close();
 pass('Packaged naming tool is widened from 360px to 440px');
 const mt=manual.locator('#nexus-native-tools');await mt.locator('#toggle').click();await mt.locator('[data-view=settings]').click();
 const localCount=await manual.evaluate(()=>[...fixtureIntervals.values()].filter(ms=>ms===15000).length);await mt.locator('[data-setting-id=eventScanner]').uncheck();await mt.locator('#saveSettings').click();await manual.waitForFunction(count=>[...fixtureIntervals.values()].filter(ms=>ms===15000).length===count,localCount-1);await mt.locator('[data-setting-id=eventScanner]').check();await mt.locator('#saveSettings').click();await manual.waitForFunction(count=>[...fixtureIntervals.values()].filter(ms=>ms===15000).length===count,localCount);pass('Same-page Settings saves also reach the live scanner across extension execution worlds');
 const download=manual.waitForEvent('download');await mt.locator('#missionDiagnostics').click();const exported=await download;assert.ok(exported.suggestedFilename().includes('Diagnostics'));
 pass('Mission diagnostic export still downloads through the central Settings button');
 const existingOptions=context.pages().find(p=>p.url().endsWith('/analytics.html'));const optionsPromise=existingOptions?Promise.resolve(existingOptions):context.waitForEvent('page');await mt.locator('#sharingSettings').click();const options=await optionsPromise;await options.waitForLoadState('domcontentloaded');report.optionsPage=options.url();report.optionsFrames=options.frames().map(f=>f.url());console.log('Options opened: '+report.optionsPage);assert.ok(/^(?:chrome-extension:\/\/[^/]+\/analytics\.html|(?:chrome|edge):\/\/extensions\/?\?options=)/.test(options.url()));await options.close();pass('Sharing & Sync shortcut opens extension options through the validated worker handler');
 // Restore defaults through Settings and verify banked coverage from the packaged files.
 await mt.locator('[data-setting-kind=features]').evaluateAll(inputs=>inputs.forEach(input=>{input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}));}));await mt.locator('#saveSettings').click();await manual.waitForFunction(()=>JSON.parse(localStorage.getItem('nexusConveniencesV1')).currency===true);await manual.reload();
 await manual.locator('#nx-missing').waitFor();await manual.locator('#vehicle_111').check();await manual.locator('#nx-missing [data-nx-requirement-tick]').waitFor();assert.ok((await manual.locator('#nx-missing').innerText()).includes('Cars to tow'));
 assert.equal(await manual.locator('#nx-missing [data-nx-requirement-tick]').count(),1);
 const building=await context.newPage();await building.goto('https://www.missionchief.co.uk/buildings/1');await building.locator('#nx-specialist-table').waitFor();await building.waitForFunction(()=>__NEXUS_BUILDING_OVERVIEW__.model?.training.find(g=>g.name==='HazMat Unit')?.trained===4);assert.ok((await building.locator('[data-nx-training="HazMat Unit"]').innerText()).includes('!'));
 pass('Enabled features render again; bundled flatbed covers two Cars to tow and partial specialist crews show orange warnings');
 const workerHost=await context.newPage();workerHost.on('pageerror',e=>report.errors.push(e.message));await workerHost.goto('https://www.missionchief.co.uk/fixture-worker-host');const attached=workerHost.waitForEvent('frameattached');await workerHost.evaluate(()=>{const f=document.createElement('iframe');f.name='mcn-v3-active-worker-fixture';f.dataset.mcnV3Worker='1';f.src='/missions/88';document.body.append(f);});
 const wf=await attached;await wf.waitForURL('**/missions/88');await wf.waitForLoadState('load');assert.equal(await wf.evaluate(()=>window.__NEXUS_COMFORT__),undefined);assert.equal(await wf.evaluate(()=>window.__NEXUS_COMMANDS__),undefined);assert.equal(await wf.evaluate(()=>window.__NEXUS_REQUIREMENT_TICKS__),undefined);
 pass('Manual conveniences remain excluded from the Auto worker');
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(error){report.failure=error.stack;report.passed=false;throw error;}finally{fs.writeFileSync('audit/settings-43-results.json',JSON.stringify(report,null,2));await context.close({reason:'Settings fixture finished'});}
console.log(JSON.stringify(report,null,2));
